# Generated by Django 5.2.6 on 2025-09-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='wishlist/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
