# Generated by Django 5.2.6 on 2025-09-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WishItem',
        ),
    ]
