# Generated by Django 5.2.6 on 2025-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlistitem_delete_wishitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='category',
            new_name='preference',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='link',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='priority',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company/Brand'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
