# Generated by Django 5.2.6 on 2025-09-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_rename_notes_wishlistitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
