# Generated by Django 5.2.6 on 2025-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_wishlistitem_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
