# Generated by Django 5.2.6 on 2025-09-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_alter_wishlistitem_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='description',
        ),
    ]
