# Generated by Django 5.2.6 on 2025-09-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_remove_wishlistitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='preference',
            field=models.CharField(blank=True, choices=[('favorite', "Stephcynie's Favorite"), ('alternative', 'Alternative'), ('giftcard', 'Gift Card')], max_length=100),
        ),
    ]
