# Generated by Django 5.2.6 on 2025-09-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='board/')),
                ('video', models.FileField(blank=True, upload_to='board/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
